// 根目录页面
import type { Metadata } from "next";
import Link from 'next/link';

export const metadata: Metadata = {
  title: "routerhome",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  team,
  analytics,
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}>) {
  return (
    <>
      <div className="container mx-auto">
          <div className="flex justify-center text-blue-500 p-6 gap-6">
              <Link href='/routerhome'>Home</Link> &nbsp;
              <Link href='/routerhome/visitior'>Visitor</Link>
          </div>
          <div className="flex gap-6">
              {team}
              {analytics}
          </div>
      </div>
      {children}
    </>
  );
}
